[package]
name = "fizzrust"
version = "0.1.0"
authors = ["Orazio Cappadonna <oraziocappadonna1999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"